mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpassword
    - MYSQL_DATABASE=mysql_db
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "D:/db/mysql/database:/var/lib/mysql"