package com.example.demo.service;

import com.example.demo.interfaces.UserRepository;
import com.example.demo.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class UserService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public String add(String name, String email){
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "saved!";
    }

    public Iterable<User> getAllUsers(){
        // This returns a Iterable<User> with the users
        return userRepository.findAll();
    }

}
